---
name: "SLURM"   # MUST BE "SLURM"
# Required
partition: "single"
job-name: "RLV"    # this will be the experiments name in slurm
num_parallel_jobs: 10
ntasks: 1
cpus-per-task: 1
mem-per-cpu: 8000
time: 1440  # in minutes
sbatch_args: # Dictionary of SBATCH keywords and arguments
  distribution: cyclic  # To have repetitions of the same exp be distributed to different nodes
slurm_log: "./slurmlog/"


---
# DEFAULT parameters (Optional)
name: "DEFAULT"   # MUST BE DEFAULT
path: "./output/rlv"   # location to save results in
repetitions: 3  # number of times one set of parameters is run
reps_per_job: 1 # number of repetitions in each job. useful for paralellization. defaults to 1.
reps_in_parallel: 8 # number of repetitions in each job that are executed in parallel. defaults to 1.

params:
  # this is where you specify all parameters needed for your experiment.
  # the tree structure you define here will be translated to a nested python dictionary
  action_space_type: 'discrete'
  env_name: 'acrobot'
  algo_name: 'sac'
  n_games: 2500
  pre_steps: 1000
  pre_training_steps: 225000
  layers: [256, 256]
  lr: 0.003

---
name: "rlv_ex"
path: "./output/rlv/"
repetitions: 5   # repeat 8 times

# Experiment Parameters
params:
  experiment_name: "rlv_exp"
  algo_name: 'rlv'
  ngames: 2000
  warmup_steps: 400
list:
  lr: [0.003, 0.006, 0.001]

---
name: "sac_ex"
path: "./output/sac/"
repetitions: 5   # repeat 8 times

# Experiment Parameters
params:
  experiment_name: 'sac_ex'
  algo_name: 'sac'
  ngames: 2000
  warmup_steps: 400
list:
  lr: [0.003, 0.006, 0.001]




